# Generated by Django 3.1.7 on 2021-03-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_contact_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
