# Generated by Django 3.1.7 on 2021-03-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210311_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
