# Generated by Django 3.1.7 on 2021-03-11 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210311_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cv_Img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
